### ISSUE TITLE
problem with roundcube

### ISSUE THREAD

**Issue by natan64** [stephanblanke/roundcube-agendav#7]
This plugins works fine but i have some problem with roundcube because 
if i add plugin in RC i cannot login and logout in to RC 

if i remove plugin from RC and loged and turn on plug all works finebut cannot logout

tested with this same rc and plugin whats yours

**Comment by stephanblanke** [comment]
Hi natan,

do you see any errors in your log files (e.g. apache) after failing to log in / log out? Could you post These logs?

It seems like the AgenDAV session creation / injection does not work in your Setup.

Best regards
Stephan

**Comment by natan64** [comment]
Hi
This is my log

10.10.0.30 - - [03/Aug/2015:12:15:02 +0200] "GET /mail/skins/larry/images/ajaxloader.gif?v=c252.1434 HTTP/1.1" 200 1769 "https://devical.roundcube.mydomain.pl/mail/skins/larry/styles.min.css?s=1399644 533" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:34.0) Gecko/20100101 Firefox/34.0"

10.10.0.30 - - [03/Aug/2015:12:15:02 +0200] "POST /mail/?_task=login HTTP/1.1" 500 559 "https://devical.roundcube.mydoamin.pl/mail/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:34.0) Gecko/20100101 Fire fox/34.0"


https://devical.roundcube.mydoamin.pl/mail/ - my roundcube
http://devical.roundcube.mydoamin.pl - my DAViCal CalDAV Server

strace process:


) = 0
epoll_wait(12, {{EPOLLIN, {u32=1909019352, u64=140494584238808}}}, 2, 10000) = 1
accept4(4, {sa_family=AF_INET, sin_port=htons(49337), sin_addr=inet_addr("10.10.0.30")}, [16], SOCK_CLOEXEC) = 13
semop(11763713, {{0, 1, SEM_UNDO}}, 1)  = 0
getsockname(13, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("86.x.x.x")}, [16]) = 0
open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 15
read(15, "\212\220A\216\353\327z\f\235\254v\3\25\347\371\n\366\242`je\n\233\227\332\203\224=\361Yq["..., 512) = 512
close(15)                               = 0
fcntl(13, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
read(13, "\26\3\1\2\0\1\0\1\374\3\3\7$\305\223\354\312\316\245#eF\243\253t\f|\315\214\363\31\361"..., 8000) = 517
writev(13, [{"\25\3\3\0\2\1p\26\3\3\0Q\2\0\0M\3\3U\277@U\323\r\250\360\2316&\350\371\326"..., 144}], 1) = 144
poll([{fd=13, events=POLLIN}], 1, 21033) = 1 ([{fd=13, revents=POLLIN}])
read(13, "\24\3\3\0\1\1\26\3\3\0(\0\0\0\0\0\0\0\0\v\6N\336.\343\270\0\177\233\374n\341"..., 8000) = 759
stat("/usr/share/apache2/roundcubemail/skins/larry/images/ajaxloader.gif", {st_mode=S_IFREG|0644, st_size=1434, ...}) = 0
open("/usr/share/apache2/roundcubemail/skins/larry/images/ajaxloader.gif", O_RDONLY|O_CLOEXEC) = 15
close(15)                               = 0
writev(13, [{"\27\3\3\0\305\204\377-Ca\347\210k\30\376\277@\3126o\263\02241M\177\207\322qar\360"..., 202}], 1) = 202
write(10, "10.10.0.30 - - [03/Aug/2015:12:2"..., 294) = 294
times({tms_utime=12, tms_stime=8, tms_cutime=0, tms_cstime=0}) = 902758195
poll([{fd=13, events=POLLIN}], 1, 5000) = 0 (Timeout)
times({tms_utime=12, tms_stime=8, tms_cutime=0, tms_cstime=0}) = 902758695
writev(13, [{"\25\3\3\0\32\204\377-Ca\347\210l\205V\333\275\2169\267+\350?\216\200\370/p\25f\247", 31}], 1) = 31
shutdown(13, 1 /* send */)              = 0
poll([{fd=13, events=POLLIN}], 1, 2000) = 1 ([{fd=13, revents=POLLIN|POLLHUP}])
read(13, "", 512)                       = 0
close(13)                               = 0
read(5, 0x7fffbd117d07, 1)              = -1 EAGAIN (Resource temporarily unavailable)

For test i change chmod for plugins/agendav to 777 and nothing and dont have idea

**Comment by stephanblanke** [comment]
Hi natan,

great to hear that the problem is solved.

Best regards
Stephan
