### ISSUE TITLE
PDOException' with message 'could not find driver'

### ISSUE THREAD

**Issue by Franck2A** [stephanblanke/roundcube-agendav#8]
Hi Stephan and thank's for your job.
I'm trying to integrate roundcube-agendav 1.2.6.2 in my rounducube 0.9.5.
When plugin is activated, i have this error after clicking on agendav icon of the roundcube menu.
*** Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/html/roundcube/plugins/agendav/agendav.php:109 Stack trace: #0 /var/www/html/roundcube/plugins/agendav/agendav.php(109): PDO->__construct(':dbname=;host=', '', '') #1 [internal function]: agendav->logout(Array) #2 /var/www/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(289): call_user_func(Array, Array) #3 /var/www/html/roundcube/program/include/rcmail.php(663): rcube_plugin_api->exec_hook('session_destroy') #4 /var/www/html/roundcube/index.php(172): rcmail->kill_session() #5 {main} thrown in /var/www/html/roundcube/plugins/agendav/agendav.php on line 109 ***

Accessory request... Do i need to install a caldav server like Davical or Roundcube + this plugin are enough.

Thank's for help and best regards.
Franck

**Comment by stephanblanke** [comment]
Hi Franck,

to use this plugin, you need a caldav server, for example SabreDAV or Davical. After downloading and installing this plugin including the integrated AgenDAV, you have to configure AgenDAV according to its documentation. This pluging reads all necessary database credentials from the AgenDAV configuration files.

Best regards
Stephan
